version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    labels: ['scope :: chore :gear:', 'status :: needs review :mag:']
    schedule:
      interval: 'monthly'
      time: '08:00'
      timezone: 'Europe/Rome'
