name: CI

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  tests:
    if: ${{ contains(github.event.pull_request.body, '[[skip-ci]]') == false }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'Install Dependencies'
        run: pnpm install --no-frozen-lockfile

      - name: 'Linters & Tests'
        run: |
          pnpm check
          pnpm test

      - name: 'Build the artifact'
        run: pnpm build
